// Code generated by mockery v1.0.0. DO NOT EDIT.

package burner

import mock "github.com/stretchr/testify/mock"
import mux "github.com/gorilla/mux"

// MockEmailProvider is an autogenerated mock type for the EmailProvider type
type MockEmailProvider struct {
	mock.Mock
}

// DeleteExpiredRoutes provides a mock function with given fields:
func (_m *MockEmailProvider) DeleteExpiredRoutes() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// RegisterRoute provides a mock function with given fields: i
func (_m *MockEmailProvider) RegisterRoute(i Inbox) (string, error) {
	ret := _m.Called(i)

	var r0 string
	if rf, ok := ret.Get(0).(func(Inbox) string); ok {
		r0 = rf(i)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(Inbox) error); ok {
		r1 = rf(i)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Start provides a mock function with given fields: websiteAddr, db, r, isBlacklisted
func (_m *MockEmailProvider) Start(websiteAddr string, db Database, r *mux.Router, isBlacklisted func(string) bool) error {
	ret := _m.Called(websiteAddr, db, r, isBlacklisted)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, Database, *mux.Router, func(string) bool) error); ok {
		r0 = rf(websiteAddr, db, r, isBlacklisted)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *MockEmailProvider) Stop() error {
	ret := _m.Called()

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
